/**
 * generate-config.js
 * Reads Firebase credentials from environment variables (or .env file)
 * and writes a config.js that the browser can load.
 *
 * Usage (local):
 *   node generate-config.js
 *
 * On Netlify / Vercel:
 *   1. Set all FIREBASE_* env vars in your hosting dashboard
 *   2. Set Build Command to: node generate-config.js
 *   3. Set Publish Directory to: ./
 */

const fs   = require('fs');
const path = require('path');

// ── Load .env if it exists (local dev) ──────────────────────────────────────
const envPath = path.join(__dirname, '.env');
if (fs.existsSync(envPath)) {
  const lines = fs.readFileSync(envPath, 'utf8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const [key, ...rest] = trimmed.split('=');
    const value = rest.join('=').trim();
    if (key && value && !process.env[key]) {
      process.env[key] = value;
    }
  }
}

// ── Validate required vars ───────────────────────────────────────────────────
const required = [
  'FIREBASE_API_KEY',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_DATABASE_URL',
  'FIREBASE_APP_ID',
];

const missing = required.filter(k => !process.env[k]);
if (missing.length) {
  console.error('❌  Missing required env vars:', missing.join(', '));
  console.error('    Fill them in .env or set them in your hosting dashboard.');
  process.exit(1);
}

// ── Write config.js ───────────────────────────────────────────────────────────
const content = `// config.js — AUTO-GENERATED by generate-config.js. DO NOT EDIT MANUALLY.
// This file is gitignored. Re-generate with: node generate-config.js

window.FIREBASE_CONFIG = {
  apiKey:            "${process.env.FIREBASE_API_KEY}",
  authDomain:        "${process.env.FIREBASE_AUTH_DOMAIN || `${process.env.FIREBASE_PROJECT_ID}.firebaseapp.com`}",
  projectId:         "${process.env.FIREBASE_PROJECT_ID}",
  storageBucket:     "${process.env.FIREBASE_STORAGE_BUCKET || `${process.env.FIREBASE_PROJECT_ID}.appspot.com`}",
  messagingSenderId: "${process.env.FIREBASE_MESSAGING_SENDER_ID || ''}",
  appId:             "${process.env.FIREBASE_APP_ID}",
  measurementId:     "${process.env.FIREBASE_MEASUREMENT_ID || ''}",
  databaseURL:       "${process.env.FIREBASE_DATABASE_URL}",
};
`;

const outPath = path.join(__dirname, 'config.js');
fs.writeFileSync(outPath, content, 'utf8');
console.log('✅  config.js generated successfully from environment variables.');
console.log('    databaseURL:', process.env.FIREBASE_DATABASE_URL);
