// Word Suspect – Word Pairs Database
const WORD_PAIRS = {
  round1: {
    name: "Everyday Objects",
    emoji: "🏠",
    color: "#FF6B6B",
    pairs: [
      { common: "Pizza", impostor: "Burger" },
      { common: "Tea", impostor: "Coffee" },
      { common: "Pen", impostor: "Pencil" },
      { common: "Car", impostor: "Bike" },
      { common: "Apple", impostor: "Orange" },
      { common: "Book", impostor: "Magazine" },
      { common: "Soap", impostor: "Shampoo" },
      { common: "Chair", impostor: "Sofa" },
      { common: "Clock", impostor: "Watch" },
      { common: "Shoes", impostor: "Sandals" },
      { common: "Milk", impostor: "Juice" },
      { common: "Plate", impostor: "Bowl" },
      { common: "Spoon", impostor: "Fork" },
      { common: "Mirror", impostor: "Window" },
      { common: "Pillow", impostor: "Blanket" },
      { common: "Umbrella", impostor: "Raincoat" },
      { common: "Key", impostor: "Lock" },
      { common: "Bag", impostor: "Backpack" },
      { common: "Bed", impostor: "Mattress" },
      { common: "Phone", impostor: "Tablet" },
    ]
  },
  round2: {
    name: "Wild Animals",
    emoji: "🦁",
    color: "#4ECDC4",
    pairs: [
      { common: "Lion", impostor: "Tiger" },
      { common: "Dog", impostor: "Wolf" },
      { common: "Horse", impostor: "Donkey" },
      { common: "Cat", impostor: "Leopard" },
      { common: "Cow", impostor: "Buffalo" },
      { common: "Elephant", impostor: "Rhino" },
      { common: "Monkey", impostor: "Gorilla" },
      { common: "Eagle", impostor: "Hawk" },
      { common: "Shark", impostor: "Dolphin" },
      { common: "Snake", impostor: "Lizard" },
      { common: "Penguin", impostor: "Seal" },
      { common: "Fox", impostor: "Coyote" },
      { common: "Bear", impostor: "Panda" },
      { common: "Rabbit", impostor: "Hare" },
      { common: "Crocodile", impostor: "Alligator" },
      { common: "Parrot", impostor: "Toucan" },
      { common: "Zebra", impostor: "Giraffe" },
      { common: "Cheetah", impostor: "Jaguar" },
      { common: "Octopus", impostor: "Squid" },
      { common: "Frog", impostor: "Toad" },
    ]
  },
  round3: {
    name: "🔥 CHAOS ROUND",
    emoji: "🎭",
    color: "#A855F7",
    pairs: [
      { common: "Batman", impostor: "Iron Man" },
      { common: "India", impostor: "Japan" },
      { common: "Instagram", impostor: "TikTok" },
      { common: "Netflix", impostor: "Prime Video" },
      { common: "Google", impostor: "Microsoft" },
      { common: "Spider-Man", impostor: "Superman" },
      { common: "McDonald's", impostor: "Burger King" },
      { common: "Nike", impostor: "Adidas" },
      { common: "Apple", impostor: "Samsung" },
      { common: "Elon Musk", impostor: "Jeff Bezos" },
      { common: "Avengers", impostor: "Justice League" },
      { common: "YouTube", impostor: "Twitch" },
      { common: "Minecraft", impostor: "Roblox" },
      { common: "Harry Potter", impostor: "Hermione" },
      { common: "France", impostor: "Italy" },
      { common: "WhatsApp", impostor: "Telegram" },
      { common: "Coca-Cola", impostor: "Pepsi" },
      { common: "Thor", impostor: "Hulk" },
      { common: "Leonardo DiCaprio", impostor: "Brad Pitt" },
      { common: "Cristiano Ronaldo", impostor: "Lionel Messi" },
    ]
  }
};
